# Generated by Django 4.2.4 on 2023-08-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.SlugField(max_length=100, unique=True)),
                ("term", models.CharField(max_length=500)),
                ("displaytext", models.CharField(max_length=500)),
                ("version", models.CharField(max_length=50)),
                ("contents", models.JSONField()),
            ],
        ),
    ]
