# Generated by Django 4.2.4 on 2023-08-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="term",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
