# Generated by Django 4.2.4 on 2023-08-05 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pages", "0002_alter_page_term"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hyperlink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.SlugField(max_length=100, unique=True)),
                ("link", models.URLField(max_length=500)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="hyperlinks", to="pages.page"
                    ),
                ),
            ],
        ),
    ]
