# Generated by Django 4.2.4 on 2023-08-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hyperlinks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hyperlink",
            name="name",
            field=models.SlugField(max_length=100),
        ),
    ]
